# Generated by Django 5.1.3 on 2024-12-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlataforma', '0002_tutor_profesor_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=50)),
                ('asignatura', models.CharField(blank=True, max_length=30)),
                ('rol', models.CharField(choices=[('tutor', 'Tutor'), ('profesor', 'Profesor')], max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='profesor_ptr',
        ),
        migrations.AddField(
            model_name='curso',
            name='dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='hora',
            field=models.CharField(default='00:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
